### ISSUE TITLE
Email notifications about paper that I am not following

### ISSUE THREAD

**Issue by tmober** [cuny-academic-commons/social-paper#101]
I received notifications about the papers below which I am NOT following, all of which appear to be provided by the same contributor:
- https://commons.gc.cuny.edu/papers/improvements-of-an-aspiring-writer/
- https://commons.gc.cuny.edu/papers/rhetorical-analysis-of-mother-tongue/
- https://commons.gc.cuny.edu/papers/depression-addiction-and-finding-a-lifelong-friend/

**Comment by r-a-y** [comment]
Thanks for reaching out, @tmober. We've already received reports about this bug and have fixed this [internally on the Commons](https://redmine.gc.cuny.edu/issues/15024).

The issue is caused by the author using a password for their paper, which triggered a bug in the email notification system for followers of that paper.

See commit https://github.com/cuny-academic-commons/social-paper/commit/41f4d831d8207379865f850374fd86279021fe1b for the fix.
