### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#2]
A big part of Social Paper will be the ability to edit in a nice front-end interface. Some requirements:
- Should be front-end - not in the Dashboard
- Should be rich-text, or roughly WYSIWYG
- Should include basic support for inserting images and other media

It's likely that much of this can be accomplished with some permutation of `wp_editor()` and the TinyMCE tools built into WordPress. It's also likely that we don't need to reinvent the wheel. So @rjbaniel, the first step here will be to do a scan of existing editor plugins. https://github.com/iseulde/wp-front-end-editor might be a starting place. I know there are other plugins that ape the Medium interface.

Note that we're assuming, for simplicity's sake, that the Edit interface will be independent of the Read/Comment interface. If it turns out that we can combine the two, that'll just be a bonus.

**Comment by r-a-y** [comment]
Another thing to think about is creating the initial post on the frontend.

In #5, I've added some code to support a paper directory (`example.com/paper/`).  Perhaps the new post URL could be `example.com/paper/new`.

I also came across a blog post detailing (probably) the majority of available frontend editor plugins:
http://translate.google.com/translate?u=https%3A%2F%2Fwww.sowmedia.nl%2Fwordpress%2Ffront-end-editor-plugin&sl=auto&tl=en

Lasso looks good and its source code is readily available on Github, but requires a license to use on production sites.  WP Front End Editor is probably what we'll end up looking at, but will probably require some tweaking for our spec.

**Comment by rjbaniel** [comment]
Added some support for a paper[or other supported CPT slug]/new URL to load a new-social-paper.php file: https://github.com/cuny-academic-commons/social-paper/commit/6d934b196b710bdd481cd65efa859b20aa175111

Still need to get that template up and running using one of the plugins you all suggested, just put in a place-holder for now. Also fixed an error in that code here, in case another plugin uses a [slug]/new URL format: https://github.com/cuny-academic-commons/social-paper/commit/85329f456d2c852d72b292b8ed37dd9238208d67

I tried to take a cue from how Buddypress handles this situation, by looking at the requested URI and using the template_include filter.

I do have a question about Edit mode - do we need to think carefully about how to do that, if comments are associated with particular paragraphs, and edits might result in the deleting and altering of paragraphs? I know this has come up before, sorry if I missed what we came up with on that. For now though I'll keep working on getting the initial creation working. Maybe we can talk more at the check-in tomorrow.

**Comment by r-a-y** [comment]
Hi Dan,

I was thinking that the `'new'` page should use our existing single social paper template, but we just change up the content to use a custom template.  See commit cb078d5 for what I had in mind.

So instead of looking at the URL to determine if we're on our `'new'` page slug, we're using the existing single page logic, but doing a bit of WP manipulation and adding a fake `'new'` page so WP will not serve a 404.  To stop WP from serving a 404, the filter on `'the_posts'` allows us to set up our dummy post.

> I tried to take a cue from how Buddypress handles this situation, by looking at the requested URI and using the template_include filter.

BuddyPress actually is not the ideal example for parsing out URLs and serving virtual pages.  Manually parsing the URI is a remnant from an older system that we have to maintain for backward compatibility reasons.  Commit cb078d5 adheres to WP's parser and doesn't try to reinvent the wheel (too much!).

> I do have a question about Edit mode - do we need to think carefully about how to do that, if comments are associated with particular paragraphs, and edits might result in the deleting and altering of paragraphs?

Good question.  I'm thinking for our needs we should hide paragraph comments when in edit mode for now until we determine what the frontend editors do when a person is doing a live edit.

**Comment by boonebgorges** [comment]
>  See commit cb078d5 for what I had in mind.

Oh, WordPress.

> I'm thinking for our needs we should hide paragraph comments when in edit mode for now until we determine what the frontend editors do when a person is doing a live edit.

Agreed. This is what I meant above about a separation between Edit mode and Read mode. In Edit mode, the user won't see comments. When the changes are saved, some recalculation will take place to try to relocate comments on altered paragraphs; see #1 for discussion.

> Lasso looks good and its source code is readily available on Github, but requires a license to use on production sites. WP Front End Editor is probably what we'll end up looking at, but will probably require some tweaking for our spec.

Thanks for this link, @r-a-y. @rjbaniel - let us know when you've had a chance to knock around a few of these plugins.

**Comment by r-a-y** [comment]
Just a note that I've merged in my changes from the `'new-paper'` branch into master and have reverted the previous commits relating to the previous attempts to load up the template for the 'new' page.

I've also created a new issue for the "New Paper" page (#8) as it's different enough to warrant its own issue.

**Comment by christianwach** [comment]
> WP Front End Editor is probably what we'll end up looking at

I used a modified version of WP Front End Editor 1.4 when I integrated it with CommentPress. The biggest issue I found with it is that it's instantiated as an anonymous object, which makes manipulating its actions and filters rather tricky. See my (still unmerged) PRs for details:

https://github.com/iseulde/wp-front-end-editor/pulls

**Comment by christianwach** [comment]
There might also be some useful code that can be grabbed from [the JS I wrote](https://github.com/IFBook/commentpress-core/blob/master/themes/commentpress-modern/assets/js/wp_fee.js) that interacts with the various triggers in WP FEE. Most of it relates to the problems encountered because CommentPress uses TinyMCE in the comment form, but there's stuff in there that could be used as boilerplate for saving metadata when the post is saved.

**Comment by rjbaniel** [comment]
I integrated the WP Front-end Editor plugin here: https://github.com/cuny-academic-commons/social-paper/commit/ed569d29e721b9582c767f4ba1257e1c76d360a1

I think this plugin looks like a great option, but could be missing something. As a heads up - in order to make it work for now I had to re-enqueue the admin bar style, because that's where they put the Edit button when you're logged in. Is this the kind of integration we were going for? At first I just installed the plugin on its own and added the integration in one of Social Paper's files, but then thought that we might just be interested in pulling their code right into our plugin. Wouldn't be hard to switch it back - works the same either way.

The way it works is it just changes the "Edit Post" button in the admin bar when you're viewing a Social Paper from a link to the admin section to a button that turns on Edit mode for the paper in the front end, and then off again when you're done. Looks like this means less of a separation between Read mode and Edit mode than we were talking about, but shouldn't be too hard to hide comments, etc. once we switch into Edit mode. There are definitely some styling and other issues to be worked out, but it does look basically functional. One thing I still have to do is figure out the registered name of the stylesheet for the Add Media modal and re-enqueue that, because it's broken right now.

There are some implications for the New Paper mode too with this plugin, but I'll leave those over there at #8  

Sorry if I'm missing something major here.

**Comment by r-a-y** [comment]
>  As a heads up - in order to make it work for now I had to re-enqueue the admin bar style, because that's where they put the Edit button when you're logged in.

Thanks for this tidbit, Dan.  Since the WP admin bar is currently disabled on social paper pages, FEE's edit link doesn't show up.  So in commit 86b5fe19, I manually added the link to the top-right corner of the page.  I also made sure that FEE's bottom toolbar is shown at all times with CSS as I think that improves usability.

> One thing I still have to do is figure out the registered name of the stylesheet for the Add Media modal and re-enqueue that, because it's broken right now.

Yeah, sorry for making this a little more complicated due to me wiping out all the style assets to disable the current theme from enqueuing its stylesheets:
https://github.com/cuny-academic-commons/social-paper/blob/master/includes/hooks-template.php#L108

I could simplify things by only dequeuing stylesheets that match the current theme slug, but that's not a 100% foolproof way of removing the current theme's stylesheet(s).

> There are some implications for the New Paper mode too with this plugin, but I'll leave those over there at #8

Thanks for getting started on that!  Will take a look tomorrow when I've had more sleep :)

**Comment by r-a-y** [comment]
>  At first I just installed the plugin on its own and added the integration in one of Social Paper's files, but then thought that we might just be interested in pulling their code right into our plugin. Wouldn't be hard to switch it back - works the same either way.

@rjbaniel - I think we should do checks for FEE and not include it directly into social-paper.

I noticed some custom post type support registration in FEE here:
https://github.com/cuny-academic-commons/social-paper/blob/master/lib/wp-front-end-editor/class-fee.php#L19

Are there any other customizations to FEE?  Or was it just that line addition?

**Comment by rjbaniel** [comment]
Nope that was the only change I made - removed lines adding support for posts and pages and added one for cacsp_paper. I can add checks and notices for FEE and pull it out of our plugin.

**Comment by christianwach** [comment]
Just a heads-up that I've found WP FEE throws errors on WP via SVN but not with 4.2.2.

**Comment by christianwach** [comment]
I've coded some compatibility with WP FEE when it's enabled as a solo plugin, though so far I've only tested this with my PRs merged. I also added a javascript file with some hooks that receive callbacks from FEE triggers so that Inline Comments (and commenting functionality in general) is faded out when WP FEE is active, then faded back in when WP FEE is disabled. When this script is included probably needs some refinement.

FWIW, I gave up trying to to make WP FEE work with WP Bleeding Edge, but it would probably be worth a bit more effort to see what's up, given that 4.3 is not too far off.

**Comment by r-a-y** [comment]
> I've coded some compatibility with WP FEE when it's enabled as a solo plugin, though so far I've only tested this with my PRs merged. I also added a javascript file with some hooks that receive callbacks from FEE triggers so that Inline Comments (and commenting functionality in general) is faded out when WP FEE is active, then faded back in when WP FEE is disabled. When this script is included probably needs some refinement.

Nice work on this so far, Christian.

Embedding media appears to work now.  Fading out the comment section is nice when edit mode is on.  Featured image support works great as well!

> FWIW, I gave up trying to to make WP FEE work with WP Bleeding Edge, but it would probably be worth a bit more effort to see what's up, given that 4.3 is not too far off.

Yeah, we'll probably need to look into this as soon as we've stablized things with FEE.

**Comment by r-a-y** [comment]
Closing this as the main edit functionality is in.
