### ISSUE TITLE
More consistent treatment for 'Create New Paper' buttons

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#54]
See comments and mockups on https://www.evernote.com/shard/s11/sh/2a92f7ca-7297-4a88-95fe-e21552e776be/3ad953afd37528809a07834a0c807e20

@r-a-y I'm assigning this to you, but if @samradd or @chris0stein have specific suggestions, it would probably be helpful.

**Comment by r-a-y** [comment]
This is a CAC-only issue.

I originally styled this on CAC so the button would look and be positioned the same as the "Create a Group" button on the Groups Directory.

When you're on your own Papers page, I styled the "New Paper" button to be the same as our "New Event" button when you're on your own Events page.  However, I just noticed that the "Create a Group" link on your own "Groups" page is styled like a tab.

Let me know what everyone wants to do here.

**Comment by samradd** [comment]
Let's keep the buttons rather than a tab. For consistency, I suggest we use 'Create New Paper' (I know it's longer, but it's also clearer), and place it on the right of the page.

Here's how that affects the current spots:
1. My Paper (Commons Profile): change to 'Create New Paper' but leave in-pace
![screen shot 2015-11-05 at 3 41 05 pm](https://cloud.githubusercontent.com/assets/7431171/10981092/a746db02-83d3-11e5-8138-c968b47ac831.png)
2. Top of hub: no change
![screen shot 2015-11-05 at 3 44 48 pm](https://cloud.githubusercontent.com/assets/7431171/10981192/4b925cd6-83d4-11e5-9412-81608d55e469.png)
3. Top of Directory: change to 'Create New Paper' and justify right
![screen shot 2015-11-05 at 3 45 13 pm](https://cloud.githubusercontent.com/assets/7431171/10981191/47aeb588-83d4-11e5-9211-2827796e55cb.png)

**Comment by r-a-y** [comment]
Thanks for the screenshots, @samradd!

Changes have been implemented and is available on cdev.
