### ISSUE TITLE
Inline Comments should be disabled everywhere but on SP paragraphs

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#65]
Inline Comment is being greedy, showing the comment bubble on paragraphs other than those in SP. I think this is a config setting. @christianwach Can you suggest how this should be set up so that it's properly sandboxed?

**Comment by r-a-y** [comment]
I've got this one.  I already started doing some CAC-only stuff for this.

As for general distribution, I didn't want to infringe too much on people that might already be using Inline Comments in some form.  Would be great to get some thoughts on this.

**Comment by boonebgorges** [comment]
Oh, right - I forgot that other people are going to be using this.

I would be happy to have this enforced in code for the Commons - it'll 
make deployment (cdev, etc) much easier. Maybe a 'pre_option_' filter.

For distribution, I'd say: let's do nothing in the code, but provide 
suggestions in the documentation.

**Comment by r-a-y** [comment]
I've removed Inline Comments from the front page and on the login page.  Let me know if you see other instances of this.

> For distribution, I'd say: let's do nothing in the code, but provide suggestions in the documentation.

Good idea!

**Comment by christianwach** [comment]
Currently, SP has a hard-coded override of whatever's set in the Inline Comments admin [here](https://github.com/cuny-academic-commons/social-paper/blob/master/includes/hooks-inline-comments.php#L38). We could add a filter at that point so that CAC can enforce a particular selector whilst letting the selector be set in the Inline Comments admin in distributed versions:

``` php
return apply_filters( 'cacsp_ic_modify_selector', 'article:not(.post-password-required) .entry-content p:visible' );
```

As for how CAC best hooks into that, I defer to your greater knowledge of the CAC setup :-)

**Comment by r-a-y** [comment]
> Currently, SP has a hard-coded override of whatever's set in the Inline Comments admin here. We could add a filter at that point so that CAC can enforce a particular selector whilst letting the selector be set in the Inline Comments admin in distributed versions.

That override is only applicable on the single social paper page.  This was done so that sites already using Inline Comments can still work properly.

We can add a filter on the Social Paper selector override if devs want to increase the selector scope on a single social paper page.  I think that's a good idea.  Will add the filter!  Thanks Christian!

**Comment by boonebgorges** [comment]
This is looking pretty good to me, so I'm going to close it in an attempt to close the milestone.
