### ISSUE TITLE
New paper mode

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/social-paper#8]
Members will need a special page to create a new paper on the frontend.
eg. `example.com/papers/new/`

Todos:
- [x] New paper creation at `/papers/new/` slug
- [x] Improve UX of FEE custom slug permalink support (somewhat addressed in commit 9020949)
- [x] FEE tag support (see #43)
- [x] FEE link papers to BP group support
- [x] Redirect to actual paper URL after publishing a new paper (see #39)

**Comment by boonebgorges** [comment]
> Also, do we allow members to link papers to groups (#3) on this page? If so, maybe we can take what we've done for bp-event-organiser and adapt it to Social Paper, but change up the CSS to make it minimalistic.

Yeah, I was planning on doing this.

**Comment by rjbaniel** [comment]
I integrated WP Front-end Editor into our plugin here: https://github.com/cuny-academic-commons/social-paper/commit/ed569d29e721b9582c767f4ba1257e1c76d360a1

The plugin does provide it's own way to create new posts using its same front-end editor - if you look in the +New drop-down in the admin bar and go down to a front-end editor enabled post type, it takes you to a front-end creation screen. It doesn't use our URL structure, but it seems like it does a whole lot of the work for us. I think it wouldn't be hard to replicate whatever JS they're using on the links in other places where we wanted to take people directly to the new paper screen. We could also use template_redirect or something else to make it so that /papers/new would still take people to that screen.

In order to make our /papers/new page work with the plugin at all with our current setup, I had to give an ID (just used -1) and a post type (cacsp_paper) to the virtual post. But then the plugin was in edit mode and not create mode, so I think we would have to do some deep diving into its JS to change its behaviour on our new paper screen to be more like creating a new post than updating an old one, even though technically it's doing the latter. I don't think that would be impossible, but don't see the plus-side out weighing the extra work.

I think the other option would just be to create our whole own interface for creating a new Social Paper, trying to borrow from the WP Front-end Editor code as much as possible.

What do you all think?

**Comment by r-a-y** [comment]
> if you look in the +New drop-down in the admin bar and go down to a front-end editor enabled post type, it takes you to a front-end creation screen. It doesn't use our URL structure, but it seems like it does a whole lot of the work for us.

Thanks for looking into this, Dan.  I agree that FEE handles a lot of the work for us, so I've decided to use FEE's method of paper creation instead of thinking about integrating `wp_editor()` ourselves.

FEE looks for a specific URL onclick to toggle new mode:
https://github.com/iseulde/wp-front-end-editor/blob/master/src/js/fee-adminbar.js#L17,L23

So commit dc12725 manually triggers this click action when on `example.com/papers/new/`.

**Comment by r-a-y** [comment]
This is pretty much completed.

Closing this one.
