### ISSUE TITLE
Enable Editing button doesn't reappear after comment toggle

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#83]
As reported in http://commons.gc.cuny.edu/?p=44409 and http://commons.gc.cuny.edu/?p=44319:

> If I click to view comments on a
> paper the “enable editing” button disappears. It does not reappear after I
> click out of the comments. To make the “enable editing” button show up
> again I have to reload the page.
> 
> I “opened” a paper I had written and the button was there. I didn’t do anything else except, click the comment bubble. The comment panel opened and the Enable Editing button disappeared. Even when I clicked back into the desktop, the button did not return.

I can't reproduce this, and I don't see in the codebase what would be making it happen. @r-a-y any ideas?

**Comment by sheesh** [comment]
To double check, I just reproduced the bug on a different computer using Firefox instead of Chrome. It happened both with a paper I published earlier as well as with a paper I created today. I noticed that after one engages with comments the URL changes to reflect this even after clicking out of the comment (e.g. http://cdev.gc.cuny.edu/papers/reproducing-a-bug/?para=P0#comment-1858). Not sure if that's relevant.

**Comment by boonebgorges** [comment]
Ah, I see now - this has to do with the way the Enable Editing button interacts with the Beta bar.

**Comment by r-a-y** [comment]
Fixed on cdev.  Make sure to purge your browser cache!

**Comment by sheesh** [comment]
Great -- works now!
