### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by christianwach** [cuny-academic-commons/social-paper#9]
So, I've run into a bit of a conundrum with Inline Comments and responsiveness. It may not be a common problem in that it only occurs when the browser window is resized, but I suspect it's going to be pretty annoying to users nonetheless. 

Inline Comments sets the location of its bubbles via inline CSS which positions them absolutely with respect to `<html>`. Side Comments, OTOH, injects its bubbles _into_ the commentable blocks which means that the bubbles track the width of the enclosing element.

Conundrum is this: whether to fix Inline Comments or adjust for it in SP's Javascript?

**Comment by r-a-y** [comment]
We could use `!important` CSS declarations in our custom CSS for responsiveness and tell Inline Comments to use `right: X%` instead of a calculated `left: Xpx` value.  This would still use absolute positioning though, but is probably the easiest way to address this.

If we can easily make Inline Comments follow a model closer to WP Side Comments, then that would be great.  But, we should also be wary of existing sites that are using Inline Comments.

**Comment by christianwach** [comment]
I'll have a go at overriding the Inline Comments positioning purely when used in a SP context.

**Comment by r-a-y** [comment]
I've sent a PR to the Inline Comments repo, which should address this:
https://github.com/kevinweber/inline-comments/pull/4

Leaving open until it has been merged.

**Comment by r-a-y** [comment]
PR has been merged.  Inline Comments v2.1.4 should address this.

**Comment by christianwach** [comment]
Nice & simple way to achieve this. Thanks @r-a-y
