### ISSUE TITLE
Change default behavior of FEE alert on leave

### ISSUE THREAD

**Issue by profstein** [cuny-academic-commons/social-paper#92]
The alert happens when the user clicks Disable Editing on a paper they have changed but not updated. 

The change would mean the default behavior if the user didn't pay attention would be to save the work they did instead of leave without saving.

Basically change from this default
![image](https://cloud.githubusercontent.com/assets/6502138/11383719/37b955b2-92d8-11e5-9418-edb99a7042ef.png)

To this instead:
![image](https://cloud.githubusercontent.com/assets/6502138/11383749/5c4979c0-92d8-11e5-9fa1-ae4ec0359772.png)

I think it might be clearer to also write Leave without update like:
![image](https://cloud.githubusercontent.com/assets/6502138/11383880/45d3cc80-92d9-11e5-9aad-2c11b2927574.png)

But it's a bit verbose and I'm willing to be overridden. Also it requires changing the width of .fee-alert-body to at least 355px.

**Comment by boonebgorges** [comment]
I don't have strong feelings about the verbosity. Changing which button is "primary" (blue) seems OK to me.

Having the primary button in the middle doesn't make a lot of sense to me. How about swapping the second and third buttons?

**Comment by profstein** [comment]
Swapping the buttons is fine with me, go ahead with that. I also don't have strong feelings about the language.  the main thing is that if they hit enter without reading it will save the changes.

On Nov 25, 2015, at 4:46 PM, Boone Gorges <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't have strong feelings about the verbosity. Changing which button is "primary" (blue) seems OK to me.

Having the primary button in the middle doesn't make a lot of sense to me. How about swapping the second and third buttons?

##

**Comment by samradd** [comment]
I agree that swapping the buttons is a good idea, so the blue one is still on the far-right. That also means we should update the text to be clearer, such as: "The changes you made will be lost if you navigate away from this page without updating." Which would look something like this (sorry, quick mock-up): 

![update-and-leave](https://cloud.githubusercontent.com/assets/7431171/11486882/cba36302-9789-11e5-9e34-703da70409dc.jpg)

Since we determined that this doesn't affect documentation (http://commons.gc.cuny.edu/?p=44725), I'd love to see this implemented prior to launch, if it isn't a heavy lift. Changing which button is dominant could create a lot of confusion if we change it once people have been using the interface for a bit.

**Comment by samradd** [comment]
Poking this thread -- I think this should be a priority change before too many more people become used to the way the buttons are arranged now.

**Comment by christianwach** [comment]
@samradd - thank you for thinking this through. I have implemented your revised dialog with text depending on the status of the paper (i.e. use "update" if published or "save" if draft or pending).

**Comment by boonebgorges** [comment]
This looks great - thanks, @christianwach ! 

The new button config caused a button to float to the next line (at least on my FF) so I adjusted the styling a bit https://github.com/cuny-academic-commons/wp-front-end-editor/commit/5e7d9d5a71a9a6d0778065dc1a9c695a21285686
